#import = ["/home/antoine/.cache/wal/colors.toml"]

[bell]
animation = "EaseOutExpo"
color = "#f0f0f0"
duration = 50

[colors.primary]
background = "#f0f0f0"

[font]
size = 10.5

[font.normal]
family = "SourceCodePro"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 30
y = 30
